<?php
require_once("config.php");
require_once("../lib/config.php");
include_once('../lib/home/config.php');
include_once("../lib_test/header.php");
?>
<?php
include_once("../lib/course/d_photo_master.php");
include_once("../lib_test/footer.php");
?>
